import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import UpperNav from "~/_components/UpperNav";
import Nav from "~/_components/Nav";
import Footer from "~/_components/Footer";
import ScrollToTop from "~/_components/ScrollToTop";

import FloatingContact from "~/_components/FloatingContact";
import DisclaimerSplash from "~/_components/DisclaimerSplash";
// import TermsDisclaimer from "~/_components/TermsDisclaimer";

export const metadata: Metadata = {
  title: "Leonard Solutions",
  description: "Generated by Leonard Solutions",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-[#222831] relative">
        <DisclaimerSplash />
        {/* <TermsDisclaimer /> */}
        <UpperNav />
        <Nav />
        {children}
        <FloatingContact />
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}