import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import UpperNav from "~/_components/UpperNav";
import Nav from "~/_components/Nav";
import Footer from "~/_components/Footer";
import ScrollToTop from "~/_components/ScrollToTop";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <UpperNav />
        <Nav />
        {children}
        <Footer />
        <ScrollToTop />
      </body>
    </html>
  );
}
