import "~/styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import UpperNav from "~/_components/UpperNav";
import Nav from "~/_components/Nav";
import Footer from "~/_components/Footer";
import ScrollToTop from "~/_components/ScrollToTop";
import Disclaimer from "~/_components/Disclaimer";
import FloatingContact from "~/_components/FloatingContact";

export const metadata: Metadata = {
  title: "Leonard Solutions",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-[#222831] relative">
        <Disclaimer />
        <UpperNav />
        <Nav />
        {children}
        <FloatingContact />
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}